apiVersion: v1
kind: Service
metadata:
  name: cloudiscoming-service
  namespace: cloudiscoming
  labels:
    app: cloudiscoming-app
spec:
  type: LoadBalancer
  selector:
    app: cloudiscoming-app
  ports:
    - protocol: TCP
      name: http
      port: 8081      
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudiscoming-deploy
  namespace: cloudiscoming
  labels:
    app: cloudiscoming-app
    test: test
spec:
  selector:
    matchLabels:
      app: cloudiscoming-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: cloudiscoming-app
    spec:
      containers:
      - name: cloudiscoming-app
        image: patrikahlen/cloudiscoming:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 443
        # livenessProbe:
        #   httpGet:
        #     path: /status
        #     port: 5000
        #   initialDelaySeconds: 3
        #   periodSeconds: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
#NOTE: comment out `volumeMounts` section for configmap and\or secret guide
        # volumeMounts:
        # - name: secret-volume
        #   mountPath: /secrets/
        # - name: config-volume
        #   mountPath: /configs/
#NOTE: comment out `volumes` section for configmap and\or secret guide
      # volumes:
      # - name: secret-volume
      #   secret:
      #     secretName: mysecret
      # - name: config-volume
      #   configMap:
      #     name: example-config #name of our configmap object
