apiVersion: v1
kind: Service
metadata:
  name: cloudiscoming-service
  namespace: cloudiscoming
  labels:
    app: cloudiscoming-app
spec:  
  type: LoadBalancer
  selector:
    app: cloudiscoming-app
  ports:
    - protocol: TCP
      name: http
      port: 80      
      targetPort: 80

# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: cloudiscoming-ingress  
#   annotations:
#     kubernetes.io/ingress.class: "traefik"
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /cloud
#         pathType: Prefix
#         backend:
#           service:
#               name: cloudiscoming-service          
#               port: 
#                 number: 80
              