apiVersion: v1
kind: Service
metadata:
  name: cloudiscoming-service
  labels:
    app: cloudiscoming-app
spec:
  type: NodePort
  selector:
    app: cloudiscoming-app
  ports:
    - protocol: TCP
      name: http
      port: 80      
      targetPort: 80